spring:
  datasource:
    url: jdbc:mysql://${mysql.host}/vaccines?createDatabaseIfNotExist=true
    username: ${mysql.username}
    password: ${mysql.password}
  profiles:
    active: dev
  liquibase:
    change-log: liquibase/master.yaml
  jpa:
    show-sql: ${show-sql:false}
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  rabbitmq:
    dynamic: true
    host: ${amqp.host}
    port: ${amqp.port}
    username: ${amqp.username}
    password: ${amqp.password}
amqp:
  queues:
    create-vaccines:
      exchange: vaccines.events
      routing-key: vaccines.create
      queue: vaccines.create.queue
server:
  port: 8080
springdoc:
  swagger-ui:
    path: swagger