mysql:
  username: root
  password: root
  host: localhost:3306

amqp:
  host: localhost
  port: 5672
  username: vaccines
  password: 123456

amqp:
  host: localhost
  port: 5672
  username: vaccines
  password: 123456

#application-dev.yaml application-${ALGUMA_COISA}.properties