name: Execute tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  execute_unit_tests:
    name: Execute unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Setup java developer kit (21)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradle tools
        run: chmod +x gradlew

      - name: Execute unit tests
        run: ./gradlew unitTests

  execute_integration_tests:
    name: Execute unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Setup java developer kit (21)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradle tools
        run: chmod +x gradlew

      - name: Execute unit tests
        run: ./gradlew integrationTests

  execute_e2e_tests:
    name: Execute unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Setup java developer kit (21)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradle tools
        run: chmod +x gradlew

      - name: Execute unit tests
        run: ./gradlew e2eTests